In [1]:
from sklearn.model_selection import train_test_split
#from sklearn.cross_validation import train_test_split
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
#path = "/content/drive/My Drive/2019_dataset/movement_daily.csv"
#path = "/content/drive/My Drive/2019_dataset/regdata.csv"
data =pd.read_csv("2019_model_dataset.csv")
data

Unnamed: 0       date2  hour  Daily Weight count  blob_sent_hourly mean  \
0              0  2019-01-01     0                 735               0.090732   
1              1  2019-01-01     1                 603               0.056407   
2              2  2019-01-01     2                 629               0.099920   
3              3  2019-01-01     3                 546               0.087828   
4              4  2019-01-01     4                 519               0.112179   
...          ...         ...   ...                 ...                    ...   
7146        7146  2019-10-31    19                1150               0.120465   
7147        7147  2019-10-31    20                1060               0.081688   
7148        7148  2019-10-31    21                 960               0.077343   
7149        7149  2019-10-31    22                 844               0.089521   
7150        7150  2019-10-31    23                 734               0.071012   

      vader_sent_hourly mean       day n hour  tweet dir  vsent dir  \
0                   0.147142   2019-01-01-0.0          0   0.000000   
1                   0.158979   2019-01-01-1.0       -132   0.011837   
2                   0.151551   2019-01-01-2.0         26  -0.007428   
3                   0.183226   2019-01-01-3.0        -83   0.031675   
4                   0.202897   2019-01-01-4.0        -27   0.019671   
...                      ...              ...        ...        ...   
7146                0.209381  2019-10-31-19.0         -9   0.061911   
7147                0.177808  2019-10-31-20.0        -90  -0.031573   
7148                0.153912  2019-10-31-21.0       -100  -0.023896   
7149                0.138465  2019-10-31-22.0       -116  -0.015447   
7150                0.192858  2019-10-31-23.0       -110   0.054393   

      bsent dir  bsent movement  tweet movement  vsent movement  \
0      0.000000               0               0               1   
1     -0.034326               0               0               1   
2      0.043513               0               1               1   
3     -0.012092               0               0               1   
4      0.024351               0               0               1   
...         ...             ...             ...             ...   
7146   0.059836               0               0               1   
7147  -0.038776               0               0               1   
7148  -0.004346               0               0               1   
7149   0.012178               0               0               1   
7150  -0.018508               0               0               1   

      vesent movement    Close    5hr MA  price dir  movement  month  \
0                   0  3700.31  3686.672      0.000         0      1   
1                   0  3689.69  3690.210      3.538         1      1   
2                   0  3690.00  3693.866      3.656         1      1   
3                   0  3693.13  3695.206      1.340         1      1   
4                   0  3692.71  3693.168     -2.038         0      1   
...               ...      ...       ...        ...       ...    ...   
7146                0  9211.04  9227.590     -5.522         0     10   
7147                0  9185.98  9221.990     -5.600         0     10   
7148                0  9126.20  9199.316    -22.674         0     10   
7149                0  9122.69  9175.172    -24.144         0     10   
7150                0  9140.85  9157.352    -17.820         0     10   

      price mov  
0           0.0  
1           1.0  
2           1.0  
3           1.0  
4           0.0  
...         ...  
7146        0.0  
7147        0.0  
7148        0.0  
7149        0.0  
7150        0.0  

[7151 rows x 20 columns]

In [3]:
vader = data["vader_sent_hourly mean"].values
blob = data["blob_sent_hourly mean"].values
tweetdir = data["tweet dir"].values
tweet_vol = data["Daily Weight count"].values
v_move = data["vsent dir"].values
b_move = data["bsent dir"].values
diff = data['price mov']
multifeat = data.filter(["vader_sent_hourly mean","blob_sent_hourly mean","tweet dir","Daily Weight count"])

In [4]:
#Kfold Cross Validation with Logistic Regression
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import KFold # import KFold
from sklearn import metrics
features = [vader,blob,tweetdir,tweet_vol,v_move,b_move]

feature = ['vader','blob','tweetdir','tweet_vol','v_move','b_move']
for i in range(len(features)):
    xbar = features[i].reshape(-1,1)
    kf = KFold(n_splits=10) # Define the split - into 2 folds 
    
    kf.get_n_splits(xbar) # returns the number of splitting iterations in the cross-validator
    #KFold(n_splits=10, random_state=None, shuffle=False)
    scores = []
    mat = np.zeros([2,2])
    for train_index, test_index in kf.split(xbar):
        #print("TRAIN:", train_index, "TEST:", test_index)
        X_train, X_test = xbar[train_index], xbar[test_index]
        y_train, y_test = diff[train_index], diff[test_index]
        logisticRegr = LogisticRegression()
        logisticRegr.fit(X_train, y_train)

        predictions = logisticRegr.predict(X_test)
        score = logisticRegr.score(X_test, y_test)
        scores.append(score)
        #print("{} Score : {}".format(feature[i],score))
        cm = metrics.confusion_matrix(y_test, predictions)
        mat += cm
        #print(cm)
    idx = np.mean(scores)
    print("{} Score : {}".format(feature[i],idx))

    print(mat)



/home/yq/.local/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/yq/.local/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/yq/.local/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/yq/.local/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/yq/.local/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to sile

vader Score : 0.5329343282415909
[[ 623. 2764.]
 [ 576. 3188.]]
blob Score : 0.5265036918388872
[[ 120. 3267.]
 [ 119. 3645.]]
tweetdir Score : 0.5258047818103685
[[  12. 3375.]
 [  16. 3748.]]


/home/yq/.local/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/yq/.local/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/yq/.local/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/yq/.local/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/yq/.local/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to sile

tweet_vol Score : 0.5111186857834903
[[ 361. 3026.]
 [ 470. 3294.]]
v_move Score : 0.5263640270344181
[[   0. 3387.]
 [   0. 3764.]]
b_move Score : 0.5263640270344181
[[   0. 3387.]
 [   0. 3764.]]


/home/yq/.local/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/yq/.local/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/yq/.local/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/yq/.local/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/yq/.local/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to sile

In [5]:
#multi feature logistic regression
x_train, x_test, y_train, y_test = train_test_split(multifeat, diff, test_size=0.20, random_state=0)
logisticRegr = LogisticRegression()
logisticRegr.fit(x_train, y_train)
predictions = logisticRegr.predict(x_test)
score = logisticRegr.score(x_test, y_test)
print("Multi feat Score : {}".format(score))
cm = metrics.confusion_matrix(y_test, predictions)
print(cm)

Multi feat Score : 0.5303983228511531
[[189 504]
 [168 570]]


/home/yq/.local/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [6]:
#svm useless
from sklearn.svm import SVC
#‘linear’, ‘poly’, ‘rbf’, ‘sigmoid’
kernels = ['linear','rbf','sigmoid']
for i in range(len(features)):
    sbar = features[i].reshape(-1,1)
    x_train, x_test, y_train, y_test = train_test_split(sbar, data["price mov"], test_size=0.20, random_state=0)
    for k in kernels:
        for deg in range(6):
            clf = SVC(kernel = k,gamma ="auto",degree = deg)
            clf.fit(x_train,y_train)
            predictions = clf.predict(x_test)
            score = clf.score(x_test,y_test)
            print("feature used {} with kernel {} with degree {} has score {}".format(feature[i],k,deg,score))
            cm = metrics.confusion_matrix(y_test,predictions)
            print(cm)

feature used vader with kernel linear with degree 0 has score 0.5157232704402516
[[  0 693]
 [  0 738]]
feature used vader with kernel linear with degree 1 has score 0.5157232704402516
[[  0 693]
 [  0 738]]
feature used vader with kernel linear with degree 2 has score 0.5157232704402516
[[  0 693]
 [  0 738]]
feature used vader with kernel linear with degree 3 has score 0.5157232704402516
[[  0 693]
 [  0 738]]
feature used vader with kernel linear with degree 4 has score 0.5157232704402516
[[  0 693]
 [  0 738]]
feature used vader with kernel linear with degree 5 has score 0.5157232704402516
[[  0 693]
 [  0 738]]
feature used vader with kernel rbf with degree 0 has score 0.5157232704402516
[[  0 693]
 [  0 738]]
feature used vader with kernel rbf with degree 1 has score 0.5157232704402516
[[  0 693]
 [  0 738]]
feature used vader with kernel rbf with degree 2 has score 0.5157232704402516
[[  0 693]
 [  0 738]]
feature used vader with kernel rbf with degree 3 has score 0.515723270440

In [8]:
from sklearn import neighbors

for i in range(len(features)):
    for j in range(1,6):
        for weights in ["uniform","distance"]:
            print(weights,j)
            print("Working on {}".format(feature[i]))
            sbar = features[i].reshape(-1,1)
            x_train, x_test, y_train, y_test = train_test_split(sbar, data["price mov"], test_size=0.20, random_state=0)
            knn = neighbors.KNeighborsClassifier(j, weights=weights)
            knn.fit(x_train, y_train)
            predictions = knn.predict(x_test)
            score = knn.score(x_test,y_test)
            print("The score is : {}".format(score))
            cm = metrics.confusion_matrix(y_test,predictions)
            print(cm)

uniform 1
Working on vader
The score is : 0.4989517819706499
[[319 374]
 [343 395]]
distance 1
Working on vader
The score is : 0.4989517819706499
[[319 374]
 [343 395]]
uniform 2
Working on vader
The score is : 0.4975541579315164
[[509 184]
 [535 203]]
distance 2
Working on vader
The score is : 0.4989517819706499
[[319 374]
 [343 395]]
uniform 3
Working on vader
The score is : 0.4912648497554158
[[312 381]
 [347 391]]
distance 3
Working on vader
The score is : 0.4912648497554158
[[311 382]
 [346 392]]
uniform 4
Working on vader
The score is : 0.4975541579315164
[[443 250]
 [469 269]]
distance 4
Working on vader
The score is : 0.493361285814116
[[315 378]
 [347 391]]
uniform 5
Working on vader
The score is : 0.5059399021663172
[[323 370]
 [337 401]]
distance 5
Working on vader
The score is : 0.49406009783368277
[[313 380]
 [344 394]]
uniform 1
Working on blob
The score is : 0.4968553459119497
[[327 366]
 [354 384]]
distance 1
Working on blob
The score is : 0.4968553459119497
[[327 366]


In [13]:
#random forest
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

features = [vader,blob,tweetdir,tweet_vol,v_move,b_move]

#X, y = load_iris(return_X_y=True)
feature = ['vader','blob','tweetdir','tweet_vol','v_move','b_move']
for i in range(len(features)):
    scores = []
    mat = np.zeros([2,2])
    for j in range(1,10):
        print("Working on {} {} estimators".format(feature[i],j*100))
        sbar = features[i].reshape(-1,1)
        x_train, x_test, y_train, y_test = train_test_split(sbar, data["price mov"], test_size=0.20, random_state=0)
        regressor = RandomForestClassifier(n_estimators=j*10, random_state=0,max_depth=2)
        regressor.fit(x_train, y_train)
        y_pred = regressor.predict(x_test)
        
        #predictions = knn.predict(x_test)
        score = regressor.score(x_test,y_test)
        #scores.append(score)
        print(confusion_matrix(y_test,y_pred))
        
        print(classification_report(y_test,y_pred))
        print(accuracy_score(y_test, y_pred))
        #print(scores)
        #print(mat)
    #print("The score is : {}".format(score))
    #cm = metrics.confusion_matrix(y_test,predictions)
    #print(cm)

Working on vader 100 estimators
[[294 399]
 [275 463]]
              precision    recall  f1-score   support

         0.0       0.52      0.42      0.47       693
         1.0       0.54      0.63      0.58       738

    accuracy                           0.53      1431
   macro avg       0.53      0.53      0.52      1431
weighted avg       0.53      0.53      0.52      1431

0.5290006988120196
Working on vader 200 estimators
[[266 427]
 [242 496]]
              precision    recall  f1-score   support

         0.0       0.52      0.38      0.44       693
         1.0       0.54      0.67      0.60       738

    accuracy                           0.53      1431
   macro avg       0.53      0.53      0.52      1431
weighted avg       0.53      0.53      0.52      1431

0.5324947589098532
Working on vader 300 estimators
[[266 427]
 [242 496]]
              precision    recall  f1-score   support

         0.0       0.52      0.38      0.44       693
         1.0       0.54      0.67 

In [18]:
#multifeat random forest
x= multifeat
y = data["price mov"]
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)
for i in range(1,10):
    classifier = RandomForestClassifier(n_estimators=i*100,max_depth=2, random_state=0)
    classifier.fit(X_train, y_train)
    y_pred = classifier.predict(X_test)
    print(confusion_matrix(y_test,y_pred))
    print(classification_report(y_test,y_pred))
    print(accuracy_score(y_test, y_pred))

[[203 490]
 [205 533]]
              precision    recall  f1-score   support

         0.0       0.50      0.29      0.37       693
         1.0       0.52      0.72      0.61       738

    accuracy                           0.51      1431
   macro avg       0.51      0.51      0.49      1431
weighted avg       0.51      0.51      0.49      1431

0.5143256464011181
[[200 493]
 [209 529]]
              precision    recall  f1-score   support

         0.0       0.49      0.29      0.36       693
         1.0       0.52      0.72      0.60       738

    accuracy                           0.51      1431
   macro avg       0.50      0.50      0.48      1431
weighted avg       0.50      0.51      0.49      1431

0.5094339622641509
[[195 498]
 [204 534]]
              precision    recall  f1-score   support

         0.0       0.49      0.28      0.36       693
         1.0       0.52      0.72      0.60       738

    accuracy                           0.51      1431
   macro avg       0.